lessorg: show basic help if called without argument.

diff --git a/lessorg b/lessorg
--- a/lessorg
+++ b/lessorg
@@ -3,6 +3,18 @@
 ##  lessorg:  uses less to display an orgmode file in the terminal with some basic syntax highlighting.
 ##  2023-01-06, MvdS:  initial version.
 
+# Check command-line arguments:
+if [ ${#} -ne 1 ]
+then
+    command=`echo ${0} |sed -e "s/^.*\///g"`  # Remove path (e.g. ./)
+    echo "${command}:  uses less to display an orgmode file in the terminal with some basic syntax highlighting."
+    echo "Error: at least one argument was expected"
+    echo "Syntax:  ${command} <orgmode file>"
+    exit 1
+fi
+
+ORGFILE=$1
+
 # Define colour codes:
 # Codes are automatically ended at EoL?  - no '\x1B[0m' needed???
 # Note: my default konsole text is already bold?
@@ -44,10 +56,7 @@ ENUM='\x1B[48;5;19m'       # Enumerate: blue BG
 TABL='\x1B[48;5;235m\x1B[38;5;14m'  # Table/hlines: cyan FG on dark grey BG
 
 
-file=`echo "$1.jot" | sed 's|\.jot\.jot|\.jot|g'`  # Add .jot, but remove duplicates
-
-
-cat $1 \
+cat $ORGFILE \
     | sed \
 	  -e "/^\* /s|.*|${H1}&${DEFFG}|" \
 	  -e "/^\*\* /s|.*|${H2}&${DEFFG}|" \
